# whitelist
branches:
  only:
  - travis

language: python
python:
  - "3.6"

install:
  - python3 -m pip install --upgrade pip
  - pip install -r requirements_headless.txt
  - pip install psutil

script:
  - python3 -m pytest --ignore bluesky/test/tcp/ --ignore bluesky/test/traffic/
