# whitelist
branches:
  only:
  - travis

language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

env:
  - RESET_SLEEP=60

script:
  - python3 -m pytest --ignore bluesky/test/tcp/ --ignore bluesky/test/traffic/
